// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/app/components/widgets/AppLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/app/components/widgets/SideBar.vue')['default']
    TopBar: typeof import('./src/app/components/widgets/TopBar.vue')['default']
  }
}

export {}
