/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/app/components/widgets/AppLogo.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SideBar: typeof import('./src/app/components/widgets/SideBar.vue')['default'];
    TopBar: typeof import('./src/app/components/widgets/TopBar.vue')['default'];
  }
}
