# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: this-dot-open-source

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}

      - name: Lint files
        run: npm run affected:lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}

      - name: Test Projects
        run: npm run affected:test

  e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}

      - name: E2E tests
        run: npm run e2e

      - name: Archive test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-results
          path: dist/cypress
          retention-days: 21
